# Generated by Django 2.1.5 on 2019-01-24 15:25

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Department',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=7, verbose_name='singkatan')),
                ('name', models.CharField(max_length=255, verbose_name='nama')),
            ],
            options={
                'verbose_name': 'fakultas',
                'verbose_name_plural': 'fakultas',
            },
        ),
        migrations.CreateModel(
            name='Major',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=7, verbose_name='singkatan')),
                ('name', models.CharField(max_length=255, verbose_name='nama')),
                ('nim_prefix', models.IntegerField(verbose_name='awalan NIM')),
                ('is_tpb', models.BooleanField(default=False, verbose_name='program TPB')),
                ('department', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='majors', to='members.Department', verbose_name='fakultas')),
            ],
            options={
                'verbose_name': 'program studi',
                'verbose_name_plural': 'program studi',
            },
        ),
        migrations.CreateModel(
            name='Member',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nim', models.IntegerField(verbose_name='NIM')),
                ('tpb_nim', models.IntegerField(null=True, verbose_name='NIM TPB')),
                ('name', models.CharField(max_length=255, verbose_name='nama lengkap')),
                ('nickname', models.CharField(max_length=255, verbose_name='nama panggilan')),
                ('gender', models.CharField(choices=[('male', 'Laki-laki'), ('female', 'Perempuan')], max_length=7, verbose_name='jenis kelamin')),
                ('birth_date', models.DateField(null=True, verbose_name='tanggal lahir')),
                ('year', models.IntegerField(verbose_name='angkatan')),
                ('line', models.CharField(blank=True, max_length=31, verbose_name='ID LINE')),
                ('phone', models.CharField(blank=True, max_length=31, verbose_name='nomor telepon')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='email')),
                ('current_address', models.CharField(blank=True, max_length=1023, verbose_name='tempat tinggal di Bandung')),
                ('origin_province', models.CharField(blank=True, max_length=255, verbose_name='provinsi asal')),
                ('origin_address', models.CharField(blank=True, max_length=1023, verbose_name='kota/daerah asal')),
                ('origin_school', models.CharField(blank=True, max_length=255, verbose_name='sekolah asal')),
                ('status', models.CharField(choices=[('active', 'Aktif'), ('graduated', 'Lulus'), ('dropped_out', 'DO'), ('on_leave', 'Cuti'), ('transferred', 'Pindah'), ('deceased', 'Meninggal')], default='active', max_length=31, verbose_name='status mahasiswa')),
                ('notes', models.TextField(blank=True)),
                ('major', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='members', to='members.Major', verbose_name='program studi')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='member', to=settings.AUTH_USER_MODEL, verbose_name='akun')),
            ],
            options={
                'verbose_name': 'anggota',
                'verbose_name_plural': 'anggota',
            },
        ),
    ]
