---

# Update package cache and install common packages

- name: Update all packages
  become: yes
  apt:
    update_cache: yes
    upgrade: safe
    autoremove: yes
  tags:
    - packages

# Set up SSH

- name: Ensure openssh-server is installed
  become: yes
  apt:
    pkg: openssh-server
    state: latest
    update_cache: true
    cache_valid_time: 3600
  notify: Restart SSH
  tags:
    - packages

- name: Disable root login
  become: yes
  when: ssh_disable_root_login
  lineinfile:
    dest: /etc/ssh/sshd_config
    regexp: '^PermitRootLogin'
    line: "PermitRootLogin no"
    state: present
  notify: Restart SSH

- name: Disable password authentication
  become: yes
  when: ssh_disable_password_auth
  lineinfile:
    dest: /etc/ssh/sshd_config
    regexp: '^PasswordAuthentication'
    line: "PasswordAuthentication no"
    state: present
  notify: Restart SSH

# Set timezone

- name: Set /etc/timezone # Not needed on newer Ubuntu systems, set /etc/localtime symlink instead
  become: yes
  copy:
    content: "{{ timezone | regex_replace('$', '\n') }}"
    dest: /etc/timezone
    owner: root
    group: root
    mode: 0644
    backup: yes
  notify: Update timezone

- name: Set /etc/localtime
  become: yes
  file:
    src: /usr/share/zoneinfo/{{ timezone }}
    dest: /etc/localtime
    state: link
    owner: root
    group: root
    mode: 0644
  notify: Update timezone

# Set up temporary swap file that persists until next reboot

- name: Create swap file
  become: yes
  command: fallocate -l {{ swap_size }} /swapfile
  when: create_swap
  args:
    creates: /swapfile
  tags:
    - swap

- name: Set swap file permissions
  become: yes
  file:
    dest: /swapfile
    mode: 0600
  when: create_swap
  tags:
    - swap

- name: Disable swap if enabled
  become: yes
  command: swapoff /swapfile
  when: create_swap
  ignore_errors: yes
  tags:
    - swap

- name: Set swappiness
  become: yes
  command: sysctl vm.swappiness={{ swappiness }}
  when: create_swap
  tags:
    - swap

- name: Format swap file
  become: yes
  command: mkswap /swapfile
  when: create_swap
  tags:
    - swap

- name: Activate swap until next reboot
  become: yes
  command: swapon /swapfile
  when: create_swap
  tags:
    - swap