---

# Install Pip and Pipenv

- name: Install Pip
  become: yes
  apt:
    name:
      - "{{ python_name }}-pip"
    update_cache: yes
    cache_valid_time: 3600
  tags:
    - packages

- name: Install Pipenv
  become: yes
  pip:
    name: pipenv
  tags:
    - packages