---

# Configure a Let's Encrypt SSL certificate using Certbot

- name: Install Certbot
  become: yes
  apt:
    name: certbot
    update_cache: yes
    cache_valid_time: 3600
  tags: packages

- name: Create Let's Encrypt webroot directory
  become: yes
  file:
    dest: "{{ letsencrypt_webroot_directory }}"
    owner: www-data
    group: www-data
    state: directory

# https://weakdh.org/
- name: Generate dhparams file
  become: yes
  command: "openssl dhparam -out /etc/letsencrypt/ssl-dhparams.pem 2048"
  args:
    creates: /etc/letsencrypt/ssl-dhparams.pem

- name: Add options-ssl-nginx.conf file
  become: yes
  template:
    src: options-ssl-nginx.conf
    dest: /etc/letsencrypt/options-ssl-nginx.conf
    owner: root
    group: root
    mode: 0644

- name: Add Nginx configuration for Let's Encrypt domain validation
  become: yes
  template:
    src: nginx_letsencrypt.j2
    dest: /etc/nginx/sites-available/letsencrypt
    owner: www-data
    group: www-data
    mode: 0644

- name: Enable Nginx configuration for Let's Encrypt domain validation
  become: yes
  file:
    src: /etc/nginx/sites-available/letsencrypt
    dest: /etc/nginx/sites-enabled/letsencrypt
    owner: www-data
    group: www-data
    state: link
  notify: Reload Nginx

- name: Check whether a Let's Encrypt SSL certificate already exists
  become: yes
  stat:
    path: /etc/letsencrypt/live/{{ fqdn }}/cert.pem
  register: letsencrypt_certificate

- name: Ensure Nginx is using latest config
  become: yes
  systemd:
    name: nginx
    state: reloaded
  when: not letsencrypt_certificate.stat.exists

- name: Generate SSL certificate using Certbot
  become: yes
  command: "certbot certonly --webroot --email {{ letsencrypt_service_admin_email }} --agree-tos --webroot-path={{ letsencrypt_webroot_directory }} -d {{ fqdn }} --non-interactive"
  when: not letsencrypt_certificate.stat.exists

# Setup cron tasks for Certbot auto-renewal of Let's Encrypt SSL certificates

- name: Add crontab to renew certificates
  become: yes
  cron:
    name: certbot-renew
    weekday: 1
    hour: 3
    minute: 16
    job: "certbot renew"
  when: letsencrypt_auto_renew
  tags:
    - cron

- name: Add crontab to reload Nginx
  become: yes
  cron:
    name: reload-nginx
    weekday: 1
    hour: 3
    minute: 30
    job: "/etc/init.d/nginx reload"
  when: letsencrypt_auto_renew
  tags:
    - cron
