---

- name: Install Certbot
  become: yes
  apt:
    name: certbot
    update_cache: yes
    cache_valid_time: 3600
  tags: packages

- name: Create Certbot webroot directory
  become: yes
  file:
    dest: "{{ certbot_webroot_directory }}"
    owner: www-data
    group: www-data
    state: directory

# https://weakdh.org/
- name: Generate dhparams file
  become: yes
  command: "openssl dhparam -out /etc/letsencrypt/ssl-dhparams.pem 2048"
  args:
    creates: /etc/letsencrypt/ssl-dhparams.pem

- name: Add options-ssl-nginx.conf file
  become: yes
  template:
    src: options-ssl-nginx.conf
    dest: /etc/letsencrypt/options-ssl-nginx.conf
    owner: root
    group: root
    mode: 0644

- name: Check whether a Certbot SSL certificate already exists
  become: yes
  stat:
    path: /etc/letsencrypt/live/{{ fqdn }}/cert.pem
  register: certbot_certificate

- name: Ensure Nginx is using latest config
  become: yes
  systemd:
    name: nginx
    state: reloaded
  when: not certbot_certificate.stat.exists

- name: Generate SSL certificate using Certbot
  become: yes
  command: "certbot certonly --webroot --email {{ certbot_service_admin_email }} --agree-tos --webroot-path={{ certbot_webroot_directory }} -d {{ fqdn }} --non-interactive"
  when: not certbot_certificate.stat.exists

- name: Replace Nginx configuration with HTTPS configuration
  become: yes
  template:
    src: pmkdata_https.j2
    dest: /etc/nginx/sites-available/pmkdata
    owner: www-data
    group: www-data
    mode: 0644
  notify: Reload Nginx

# Auto-renew certificates

- name: Add crontab to renew certificates
  become: yes
  cron:
    name: certbot-renew
    weekday: 1
    hour: 3
    minute: 16
    job: "certbot renew"
  when: certbot_auto_renew

- name: Add crontab to reload Nginx
  become: yes
  cron:
    name: reload-nginx
    weekday: 1
    hour: 3
    minute: 30
    job: "/etc/init.d/nginx reload"
  when: certbot_auto_renew
