---

- name: Install Nginx
  become: yes
  apt:
    name: nginx
    update_cache: yes
    cache_valid_time: 3600
  tags:
    - packages

- name: Allow Nginx traffic through firewall
  become: yes
  ufw:
    rule: allow
    name: Nginx Full
  tags:
    - firewall

- import_tasks: configure-letsencrypt.yml
  when: use_letsencrypt
